# Proof of concept for shared release brancher workflow
# See SHIP-0038: https://github.com/shipwright-io/community/pull/194
name: Create Release Branch
  on:
    workflow_dispatch:
      inputs:
        release-version:
          required: true
          type: string
          description: "Semantic version for the release branch (vX.Y format)"
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    uses: adambkaplan/.github/workflows/release-branch.yml@main
    with:
      release-version: ${{ inputs.release-version }}
